-- MySQL Script generated by MySQL Workbench
-- Tue 05 Dec 2023 04:06:51 PM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PRODUIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUIT` (
  `ID_PRODUIT` INT GENERATED ALWAYS AS (),
  `imageProduit` VARCHAR(45) NOT NULL,
  `nomProduit` VARCHAR(45) NOT NULL,
  `prixProduit` INT UNSIGNED NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employe` (
  `ID_EMPLOYE` INT(100) UNSIGNED ZEROFILL NOT NULL,
  `NOM_EMPLOYE` VARCHAR(45) NULL,
  `TELEPHONE` INT(10) NULL,
  `EMAIL` VARCHAR(255) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ligne de comand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ligne de comand` (
  `ID_LIGNE` INT NOT NULL,
  `qte` INT UNSIGNED NULL,
  `ID_PRODUIT` INT UNSIGNED NOT NULL,
  `prixTotal` INT UNSIGNED NULL,
  INDEX `ID_PRODUIT_idx` (`ID_PRODUIT` ASC) VISIBLE,
  CONSTRAINT `ID_PRODUIT`
    FOREIGN KEY (`ID_PRODUIT`)
    REFERENCES `mydb`.`PRODUIT` (`ID_PRODUIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMMANDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMMANDE` (
  `ID_COMMANDE` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `NUM_COMMANDE_QUOTIDIENNE` INT UNSIGNED ZEROFILL NULL,
  `MONTANT_COMMANDE` FLOAT NULL,
  `DATE_HEURE` DATETIME NULL,
  `id_ligne` INT(100) UNSIGNED NOT NULL,
  `ID_EMPLOYE` INT(100) UNSIGNED NOT NULL,
  INDEX `ID_LIGNE_idx` (`id_ligne` ASC) VISIBLE,
  INDEX `ID_EMPLOYER_idx` (`ID_EMPLOYE` ASC) VISIBLE,
  CONSTRAINT `ID_EMPLOYE`
    FOREIGN KEY (`ID_EMPLOYE`)
    REFERENCES `mydb`.`Employe` (`ID_EMPLOYE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_LIGNE`
    FOREIGN KEY (`id_ligne`)
    REFERENCES `mydb`.`ligne de comand` (`ID_LIGNE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table2` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table3` (
)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
